[tool.poetry]
name = "etb-db"
version = "0.1.0"
description = "A very simple class for interacting with MySQL and PostgreSQL databases"
authors = ["Tate Button <yg3bpwn0or679hau8fxi@duck.com>"]
readme = "README.md"
license = "LICENSE"

[tool.poetry.dependencies]
python = "^3.10"
sqlalchemy = "^2.0.24"
psycopg2-binary = "^2.9.9"
mysql-connector-python = "^8.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
