[tool.poetry]
name = "ghexplorer"
version = "0.0.4"
description = "A GitHub Explorer"
authors = [
    "Tan Li <tan@tanli.dev>",
    "Kejie Zhang <kejiezhang000@gmail.com>",
    "Yang Qiao <serenaqiaoo@gmail.com>",
]
readme = "README.md"
repository = "https://github.com/WorkshopHQ/ghagent"
packages = [
    { include = "ghagent" },
]

[tool.poetry.dependencies]
python = "^3.10"
duckdb = "^0.9.2"
faiss-cpu = "^1.7.4"
fastapi = "^0.105.0"
gradio = "^4.11.0"
lancedb = "^0.4.0"
leptonai = "^0.10.6"
modal = "^0.56.4362"
numpy = "^1.26.2"
pyarrow = "^14.0.2"
python-dotenv = "^1.0.0"
requests = "^2.31.0"
sentence-transformers = "^2.2.2"
tqdm = "^4.66.1"
boto3 = "^1.34.5"
typer = "^0.9.0"
rich = "^13.7.0"
textual = "^0.46.0"
textual-dev = "^1.3.0"

[tool.poetry.scripts]
gha = 'ghagent.cli:cli'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
