[tool.poetry]
name = "BAET"
version = "0.1.3"
description = "A tool to bulk extract audio tracks from video using FFmpeg"
authors = ["TimeTravelPenguin <TimeTravelPenguin@gmail.com>"]
readme = "README.md"
packages = [{ include = "BAET", from = "src" }]
classifiers = [
    "Environment :: Console",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Multimedia :: Sound/Audio :: Conversion",
    "Topic :: Multimedia :: Video :: Conversion",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Typing :: Typed",
]

[project.urls]
homepage = "https://github.com/TimeTravelPenguin/BulkAudioExtractTool"

[tool.poetry.scripts]
baet = "BAET.__main__:main"

[tool.poetry.dev-dependencies]
black = "*"
isort = "*"
mypy = "*"
pre-commit = "^3.6.0"
pylint = "*"
pytest = "^7.4.4"
types-pygments = "^2.17.0.0"

[tool.poetry.dependencies]
python = ">=3.11"
asyncio = "^3.4.3"
bidict = "^0.22.1"
ffmpeg-python = "^0.2.0"
more-itertools = "^10.1.0"
pydantic = "^2.5.2"
rich = "^13.7.0"
rich-argparse = "^1.4.0"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.mypy]
mypy_path = "src"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.poetry-dynamic-versioning]
enable = false
metadata = false
vcs = "git"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
