[tool.poetry]
name = "lemon-rag"
version = "0.1.76"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
peewee = "^3.13.2"
pydantic = "1.10.12"
requests = "^2.31.0"
typing_extensions = "4.7.1"
sanic = "19.12.2"
aiohttp = "^3.9.1"
pymilvus = "2.3.4"
langchain = "0.0.352"
openai = "0.27.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
