[build-system]
requires = ['hatchling >= 1.0.1']
build-backend = "hatchling.build"

[project]
name = 'lets-go'
description = 'A simple Go game in terminal environment'
readme = 'README.md'
requires-python = '>= 3.7'
license = {file = 'LICENSE'}
authors = [
    {name = 'Brooks Su', email = 'yipeng00@gmail.com'},
]
keywords = [
    'go', 'game', 'terminal', 'weiqi', 'alphago', 'ltermio',
]
classifiers = [
    'License :: OSI Approved :: Apache Software License',
    'Natural Language :: English',
    'Operating System :: Unix',
    'Operating System :: POSIX',
    'Operating System :: MacOS :: MacOS X',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Environment :: Console',
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: End Users/Desktop',
    'Topic :: Games/Entertainment',
    'Topic :: Games/Entertainment :: Board Games',
]
dependencies = ['ltermio >= 0.6.3',]
dynamic = ['version',]

[project.urls]
Homepage = 'https://github.com/brookssu/lets-go'

[project.scripts]
lets-go = 'lets_go:main'

[tool.hatch.version]
path = 'lets_go/__init__.py'

[tool.hatch.build.targets.sdist]
include = ['/lets_go', 'CHANGELOG', 'gameshot.png']

[tool.hatch.build.targets.wheel]
include = ['/lets_go/*', 'gameshot.png']
