[tool.poetry]
name = "authentikate"
version = "0.1.10"
description = ""
authors = ["jhnnsrs <jhnnsrs@gmail.com>"]
readme = "README.md"
license = "MIT"
packages = [{ include = "authentikate" }]

[tool.poetry.dependencies]
python = "^3.10"
pyjwt = "^2.8.0"
pydantic = "<2"
django-guardian = "^2.4.0"


[tool.mypy]
exclude = ["venv/", "tests/", "examples/"]
plugins = ["mypy_django_plugin.main","pydantic.mypy"]
ignore_missing_imports = true
strict = true


[tool.django-stubs]
django_settings_module = "test_project.settings"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "test_project.settings"

[tool.poetry.group.dev.dependencies]
django = "^4.2.4"
pytest-django = "^4.5.2"
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
mypy = "^1.7.1"
cryptography = "^41.0.3"
ruff = "^0.0.282"
black = ">=22"
strawberry-graphql = "^0.216.1"
django-stubs = "^4.2.7"
strawberry-graphql-django = "^0.28.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
# Enable the pycodestyle (`E`) and Pyflakes (`F`) rules by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
extend-select = ["ANN", "D1"]
extend-ignore = ["ANN101", "ANN002", "ANN003", "D100", "ANN401"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "tests",
    "examples",
    "**/migrations",
]

# Same as Black.
line-length = 300


# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []



# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10.
target-version = "py310"
