[project]
name = "LoggerBek"
version = "0.0.1"
authors = [
  { name="BekAncer", email="bek.mag.09@gmail.com" },
]
description = "A small logger lib"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://gitlab.com/BekAncer/logginglib/-/tree/dev?ref_type=heads"
Issues = "https://gitlab.com/BekAncer/logginglib/-/issues"