[tool.poetry]
name = "etb-env"
version = "0.1.0"
description = "A very simple class for getting ENV variables"
authors = ["Tate Button <yg3bpwn0or679hau8fxi@duck.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
